# Generated by Django 5.2.4 on 2025-07-11 12:59

import django.db.models.deletion
import scout_content.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[("SONG", "غنية"), ("CHANT", "صيحة"), ("CLAP", "صفقة")],
                        max_length=50,
                    ),
                ),
                (
                    "lyrics",
                    models.TextField(
                        blank=True, help_text="Full chant/song lyrics", null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CAMPFIRE", "Campfire"),
                            ("MARCHING", "Marching"),
                            ("TRADITIONAL", "Traditional"),
                            ("FUN", "Fun"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scout_content.models.get_upload_path,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
