# Generated by Django 5.2.4 on 2025-07-20 12:30

import scout_content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scout_content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a video file (e.g., MP4, MOV).",
                null=True,
                upload_to=scout_content.models.get_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="music",
            name="web_link",
            field=models.URLField(
                blank=True,
                help_text="Link to a video or resource (e.g., YouTube).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="Upload an audio file (e.g., MP3, WAV).",
                null=True,
                upload_to=scout_content.models.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="type",
            field=models.CharField(
                choices=[("SONG", "Song"), ("CHANT", "Chant"), ("CLAP", "Clap")],
                max_length=50,
            ),
        ),
    ]
