# Generated by Django 5.2.4 on 2025-08-02 13:45

import django.db.models.deletion
import scout_content.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scout_content", "0002_music_video_file_music_web_link_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("KNOT", "عقدة"),
                            ("LASHING_1", "ربطة 1"),
                            ("LASHING_2", "ربطة 2"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("PIONEERING", "عمل ريادي"), ("KNOTS", "عقد")],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")]
                    ),
                ),
                ("usage", models.TextField(help_text="Usage of the knot or lashing")),
                ("youtube_link", models.URLField(blank=True, null=True)),
                (
                    "model_3d",
                    models.URLField(
                        blank=True,
                        help_text="Link to a 3D model (e.g., on Sketchfab)",
                        null=True,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=scout_content.models.get_scout_upload_path,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scout_content.models.get_scout_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
